apiVersion: v1
kind: Service
metadata:
  name: fulfillment-service
  namespace: eventflow
  labels:
    app: fulfillment-service
    app.kubernetes.io/part-of: eventflow
spec:
  type: ClusterIP
  selector:
    app: fulfillment-service
  ports:
    - name: http
      port: 8081
      targetPort: http
